### ISSUE TITLE
Show Internal Functions in a Node

### ISSUE THREAD

**Issue by sibusiso16** [mexindian/ShinyTester#12]
Hi Amit,

Thanks for a great package.

Can you please add a functionality in the package that shows the functions used in each node. For example, if I look at a filtered node, I would like to see the functions used in it, e.g. select(), filter(), gsub().

Regards,
Sbusiso

**Comment by DataStrategist** [comment]
Checkout the latest version. Should have the documentation and everything. Testing appreciated.

**Comment by sibusiso16** [comment]
Thanks Amit. I will test it. Thanks again for the quick turn around time in doing the enhancement.
